(define (problem problema-h5-r5)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 - habitacio
             res0 res1 res2 res3 res4 - reserva)
   (:init
         (= (capacitat hab0) 4)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 3)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 4)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 2)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 1)
         (= (ultim-dia-ocupada hab4) 0)
         (= (persones res0) 3)
         (= (principi res0) 9)
         (= (final res0) 13)
         (= (persones res1) 1)
         (= (principi res1) 10)
         (= (final res1) 20)
         (= (persones res2) 3)
         (= (principi res2) 8)
         (= (final res2) 12)
         (= (persones res3) 4)
         (= (principi res3) 17)
         (= (final res3) 23)
         (= (persones res4) 1)
         (= (principi res4) 17)
         (= (final res4) 24)
         (= (reserves-no-satisfetes) 0)
         (= (habitacions-obertes) 0)
         (= (desaprofitament-places) 0)
   )
   (:goal  (and (forall (?res - reserva) (processada ?res)) (forall (?hab - habitacio) (decidida ?hab))))
   (:metric minimize (+ (+ (* 1 (reserves-no-satisfetes)) (* 1 (desaprofitament-places))) (* 1 (habitacions-obertes))))
)
