(define (problem problema-h2-r2)
   (:domain reserves)
   (:objects hab0 hab1 - habitacio
             res0 res1 - reserva)
   (:init
         (= (capacitat hab0) 4)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 1)
         (= (ultim-dia-ocupada hab1) 0)
         (= (persones res0) 4)
         (= (principi res0) 10)
         (= (final res0) 25)
         (= (persones res1) 1)
         (= (principi res1) 16)
         (= (final res1) 24)
         (= (reserves-no-satisfetes) 0)
         (= (habitacions-obertes) 0)
         (= (desaprofitament-places) 0)
   )
   (:goal  (and (forall (?res - reserva) (processada ?res)) (forall (?hab - habitacio) (decidida ?hab))))
   (:metric minimize (+ (+ (* 1 (reserves-no-satisfetes)) (* 1 (desaprofitament-places))) (* 1 (habitacions-obertes))))
)
