(define (problem problema-h7-r7)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 hab5 hab6 - habitacio
             res0 res1 res2 res3 res4 res5 res6 - reserva)
   (:init
         (= (capacitat hab0) 1)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 4)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 3)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 2)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 4)
         (= (ultim-dia-ocupada hab4) 0)
         (= (capacitat hab5) 1)
         (= (ultim-dia-ocupada hab5) 0)
         (= (capacitat hab6) 2)
         (= (ultim-dia-ocupada hab6) 0)
         (= (persones res0) 4)
         (= (principi res0) 21)
         (= (final res0) 24)
         (= (persones res1) 1)
         (= (principi res1) 4)
         (= (final res1) 29)
         (= (persones res2) 1)
         (= (principi res2) 17)
         (= (final res2) 26)
         (= (persones res3) 4)
         (= (principi res3) 10)
         (= (final res3) 29)
         (= (persones res4) 4)
         (= (principi res4) 6)
         (= (final res4) 23)
         (= (persones res5) 2)
         (= (principi res5) 11)
         (= (final res5) 26)
         (= (persones res6) 3)
         (= (principi res6) 27)
         (= (final res6) 29)
         (= (reserves-no-satisfetes) 0)
         (= (habitacions-obertes) 0)
         (= (desaprofitament-places) 0)
   )
   (:goal  (and (forall (?res - reserva) (processada ?res)) (forall (?hab - habitacio) (decidida ?hab))))
   (:metric minimize (+ (+ (* 1 (reserves-no-satisfetes)) (* 1 (desaprofitament-places))) (* 1 (habitacions-obertes))))
)
