(define (problem problema-h5-r5)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 - habitacio
             res0 res1 res2 res3 res4 - reserva)
   (:init
         (= (capacitat hab0) 1)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 4)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 4)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 4)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 3)
         (= (ultim-dia-ocupada hab4) 0)
         (= (persones res0) 1)
         (= (principi res0) 2)
         (= (final res0) 19)
         (= (persones res1) 1)
         (= (principi res1) 9)
         (= (final res1) 12)
         (= (persones res2) 3)
         (= (principi res2) 25)
         (= (final res2) 30)
         (= (persones res3) 2)
         (= (principi res3) 25)
         (= (final res3) 30)
         (= (persones res4) 4)
         (= (principi res4) 10)
         (= (final res4) 13)
         (= (reserves-satisfetes) 0)
   
   (:goal (forall (?res - reserva) (processada ?res)))
   (:metric maximize (reserves-satisfetes))
)
