(define (problem problema-h10-r10)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 hab5 hab6 hab7 hab8 hab9 - habitacio
             res0 res1 res2 res3 res4 res5 res6 res7 res8 res9 - reserva)
   (:init
         (= (capacitat hab0) 4)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 2)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 4)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 2)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 4)
         (= (ultim-dia-ocupada hab4) 0)
         (= (capacitat hab5) 2)
         (= (ultim-dia-ocupada hab5) 0)
         (= (capacitat hab6) 3)
         (= (ultim-dia-ocupada hab6) 0)
         (= (capacitat hab7) 2)
         (= (ultim-dia-ocupada hab7) 0)
         (= (capacitat hab8) 4)
         (= (ultim-dia-ocupada hab8) 0)
         (= (capacitat hab9) 4)
         (= (ultim-dia-ocupada hab9) 0)
         (= (persones res0) 2)
         (= (principi res0) 14)
         (= (final res0) 27)
         (= (persones res1) 2)
         (= (principi res1) 28)
         (= (final res1) 29)
         (= (persones res2) 3)
         (= (principi res2) 5)
         (= (final res2) 24)
         (= (persones res3) 2)
         (= (principi res3) 20)
         (= (final res3) 23)
         (= (persones res4) 2)
         (= (principi res4) 10)
         (= (final res4) 27)
         (= (persones res5) 4)
         (= (principi res5) 1)
         (= (final res5) 7)
         (= (persones res6) 1)
         (= (principi res6) 29)
         (= (final res6) 30)
         (= (persones res7) 2)
         (= (principi res7) 8)
         (= (final res7) 25)
         (= (persones res8) 1)
         (= (principi res8) 18)
         (= (final res8) 26)
         (= (persones res9) 3)
         (= (principi res9) 7)
         (= (final res9) 23)
         (= (reserves-no-satisfetes) 0)
         (= (habitacions-obertes) 0)
         (= (desaprofitament-places) 0)
         (not (decidida hab0))
         (not (decidida hab1))
         (not (decidida hab2))
         (not (decidida hab3))
         (not (decidida hab4))
         (not (decidida hab5))
         (not (decidida hab6))
         (not (decidida hab7))
         (not (decidida hab8))
         (not (decidida hab9))
   )
   (:goal  (and (forall (?res - reserva) (processada ?res)) (forall (?res - habitacio) (decidida ?res))))
   (:metric minimize (+ (+ (* 1 (reserves-no-satisfetes)) (* 1 (desaprofitament-places))) (* 1 (habitacions-obertes))))
)
