(define (problem problema-h10-r10)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 hab5 hab6 hab7 hab8 hab9 - habitacio
             res0 res1 res2 res3 res4 res5 res6 res7 res8 res9 - reserva)
   (:init
         (= (capacitat hab0) 3)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 2)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 1)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 1)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 2)
         (= (ultim-dia-ocupada hab4) 0)
         (= (capacitat hab5) 3)
         (= (ultim-dia-ocupada hab5) 0)
         (= (capacitat hab6) 2)
         (= (ultim-dia-ocupada hab6) 0)
         (= (capacitat hab7) 4)
         (= (ultim-dia-ocupada hab7) 0)
         (= (capacitat hab8) 2)
         (= (ultim-dia-ocupada hab8) 0)
         (= (capacitat hab9) 3)
         (= (ultim-dia-ocupada hab9) 0)
         (= (persones res0) 3)
         (= (principi res0) 17)
         (= (final res0) 25)
         (= (persones res1) 3)
         (= (principi res1) 19)
         (= (final res1) 20)
         (= (persones res2) 4)
         (= (principi res2) 23)
         (= (final res2) 26)
         (= (persones res3) 2)
         (= (principi res3) 4)
         (= (final res3) 25)
         (= (persones res4) 3)
         (= (principi res4) 3)
         (= (final res4) 6)
         (= (persones res5) 1)
         (= (principi res5) 27)
         (= (final res5) 29)
         (= (persones res6) 1)
         (= (principi res6) 18)
         (= (final res6) 26)
         (= (persones res7) 4)
         (= (principi res7) 22)
         (= (final res7) 24)
         (= (persones res8) 3)
         (= (principi res8) 3)
         (= (final res8) 9)
         (= (persones res9) 1)
         (= (principi res9) 6)
         (= (final res9) 13)
         (= (reserves-no-satisfetes) 0)
         (= (habitacions-obertes) 0)
         (= (desaprofitament-places) 0)
   )
   (:goal  (and (forall (?res - reserva) (processada ?res)) (forall (?res - habitacio) (decidida ?res))))
   (:metric minimize (+ (+ (* 1 (reserves-no-satisfetes)) (* 1 (desaprofitament-places))) (* 1 (habitacions-obertes))))
)
