(define (problem problema-h10-r10)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 hab5 hab6 hab7 hab8 hab9 - habitacio
             res0 res1 res2 res3 res4 res5 res6 res7 res8 res9 - reserva)
   (:init
         (= (capacitat hab0) 1)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 4)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 4)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 2)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 1)
         (= (ultim-dia-ocupada hab4) 0)
         (= (capacitat hab5) 4)
         (= (ultim-dia-ocupada hab5) 0)
         (= (capacitat hab6) 1)
         (= (ultim-dia-ocupada hab6) 0)
         (= (capacitat hab7) 3)
         (= (ultim-dia-ocupada hab7) 0)
         (= (capacitat hab8) 2)
         (= (ultim-dia-ocupada hab8) 0)
         (= (capacitat hab9) 3)
         (= (ultim-dia-ocupada hab9) 0)
         (= (persones res0) 2)
         (= (principi res0) 3)
         (= (final res0) 9)
         (= (persones res1) 1)
         (= (principi res1) 15)
         (= (final res1) 24)
         (= (persones res2) 3)
         (= (principi res2) 28)
         (= (final res2) 29)
         (= (persones res3) 3)
         (= (principi res3) 7)
         (= (final res3) 11)
         (= (persones res4) 1)
         (= (principi res4) 7)
         (= (final res4) 30)
         (= (persones res5) 1)
         (= (principi res5) 15)
         (= (final res5) 29)
         (= (persones res6) 1)
         (= (principi res6) 1)
         (= (final res6) 15)
         (= (persones res7) 3)
         (= (principi res7) 14)
         (= (final res7) 26)
         (= (persones res8) 4)
         (= (principi res8) 26)
         (= (final res8) 28)
         (= (persones res9) 1)
         (= (principi res9) 17)
         (= (final res9) 26)
         (= (reserves-satisfetes) 0)
   )
   (:goal (forall (?res - reserva) (processada ?res)))
   (:metric maximize (reserves-satisfetes))
)
