(define (problem problema-h15-r15)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 hab5 hab6 hab7 hab8 hab9 hab10 hab11 hab12 hab13 hab14 - habitacio
             res0 res1 res2 res3 res4 res5 res6 res7 res8 res9 res10 res11 res12 res13 res14 - reserva)
   (:init
         (= (capacitat hab0) 3)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 1)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 2)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 3)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 2)
         (= (ultim-dia-ocupada hab4) 0)
         (= (capacitat hab5) 2)
         (= (ultim-dia-ocupada hab5) 0)
         (= (capacitat hab6) 2)
         (= (ultim-dia-ocupada hab6) 0)
         (= (capacitat hab7) 4)
         (= (ultim-dia-ocupada hab7) 0)
         (= (capacitat hab8) 1)
         (= (ultim-dia-ocupada hab8) 0)
         (= (capacitat hab9) 3)
         (= (ultim-dia-ocupada hab9) 0)
         (= (capacitat hab10) 1)
         (= (ultim-dia-ocupada hab10) 0)
         (= (capacitat hab11) 4)
         (= (ultim-dia-ocupada hab11) 0)
         (= (capacitat hab12) 2)
         (= (ultim-dia-ocupada hab12) 0)
         (= (capacitat hab13) 3)
         (= (ultim-dia-ocupada hab13) 0)
         (= (capacitat hab14) 2)
         (= (ultim-dia-ocupada hab14) 0)
         (= (persones res0) 3)
         (= (principi res0) 15)
         (= (final res0) 29)
         (= (persones res1) 3)
         (= (principi res1) 25)
         (= (final res1) 26)
         (= (persones res2) 4)
         (= (principi res2) 8)
         (= (final res2) 10)
         (= (persones res3) 3)
         (= (principi res3) 24)
         (= (final res3) 28)
         (= (persones res4) 2)
         (= (principi res4) 11)
         (= (final res4) 16)
         (= (persones res5) 4)
         (= (principi res5) 11)
         (= (final res5) 29)
         (= (persones res6) 4)
         (= (principi res6) 22)
         (= (final res6) 23)
         (= (persones res7) 4)
         (= (principi res7) 29)
         (= (final res7) 30)
         (= (persones res8) 3)
         (= (principi res8) 5)
         (= (final res8) 10)
         (= (persones res9) 1)
         (= (principi res9) 7)
         (= (final res9) 12)
         (= (persones res10) 4)
         (= (principi res10) 7)
         (= (final res10) 12)
         (= (persones res11) 4)
         (= (principi res11) 12)
         (= (final res11) 27)
         (= (persones res12) 1)
         (= (principi res12) 1)
         (= (final res12) 29)
         (= (persones res13) 2)
         (= (principi res13) 7)
         (= (final res13) 12)
         (= (persones res14) 3)
         (= (principi res14) 16)
         (= (final res14) 20)
         (= (reserves-satisfetes) 0)
   )
   (:goal (forall (?res - reserva) (processada ?res)))
   (:metric maximize (reserves-satisfetes))
)
