(define (problem problema-h25-r25)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 hab5 hab6 hab7 hab8 hab9 hab10 hab11 hab12 hab13 hab14 hab15 hab16 hab17 hab18 hab19 hab20 hab21 hab22 hab23 hab24 - habitacio
             res0 res1 res2 res3 res4 res5 res6 res7 res8 res9 res10 res11 res12 res13 res14 res15 res16 res17 res18 res19 res20 res21 res22 res23 res24 - reserva)
   (:init
         (= (capacitat hab0) 3)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 1)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 1)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 4)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 3)
         (= (ultim-dia-ocupada hab4) 0)
         (= (capacitat hab5) 3)
         (= (ultim-dia-ocupada hab5) 0)
         (= (capacitat hab6) 4)
         (= (ultim-dia-ocupada hab6) 0)
         (= (capacitat hab7) 4)
         (= (ultim-dia-ocupada hab7) 0)
         (= (capacitat hab8) 3)
         (= (ultim-dia-ocupada hab8) 0)
         (= (capacitat hab9) 2)
         (= (ultim-dia-ocupada hab9) 0)
         (= (capacitat hab10) 2)
         (= (ultim-dia-ocupada hab10) 0)
         (= (capacitat hab11) 1)
         (= (ultim-dia-ocupada hab11) 0)
         (= (capacitat hab12) 4)
         (= (ultim-dia-ocupada hab12) 0)
         (= (capacitat hab13) 3)
         (= (ultim-dia-ocupada hab13) 0)
         (= (capacitat hab14) 4)
         (= (ultim-dia-ocupada hab14) 0)
         (= (capacitat hab15) 2)
         (= (ultim-dia-ocupada hab15) 0)
         (= (capacitat hab16) 4)
         (= (ultim-dia-ocupada hab16) 0)
         (= (capacitat hab17) 3)
         (= (ultim-dia-ocupada hab17) 0)
         (= (capacitat hab18) 1)
         (= (ultim-dia-ocupada hab18) 0)
         (= (capacitat hab19) 3)
         (= (ultim-dia-ocupada hab19) 0)
         (= (capacitat hab20) 4)
         (= (ultim-dia-ocupada hab20) 0)
         (= (capacitat hab21) 4)
         (= (ultim-dia-ocupada hab21) 0)
         (= (capacitat hab22) 4)
         (= (ultim-dia-ocupada hab22) 0)
         (= (capacitat hab23) 4)
         (= (ultim-dia-ocupada hab23) 0)
         (= (capacitat hab24) 1)
         (= (ultim-dia-ocupada hab24) 0)
         (= (persones res0) 1)
         (= (principi res0) 16)
         (= (final res0) 30)
         (= (persones res1) 2)
         (= (principi res1) 29)
         (= (final res1) 30)
         (= (persones res2) 3)
         (= (principi res2) 26)
         (= (final res2) 28)
         (= (persones res3) 3)
         (= (principi res3) 27)
         (= (final res3) 29)
         (= (persones res4) 1)
         (= (principi res4) 10)
         (= (final res4) 17)
         (= (persones res5) 1)
         (= (principi res5) 21)
         (= (final res5) 23)
         (= (persones res6) 2)
         (= (principi res6) 20)
         (= (final res6) 25)
         (= (persones res7) 1)
         (= (principi res7) 10)
         (= (final res7) 29)
         (= (persones res8) 3)
         (= (principi res8) 27)
         (= (final res8) 28)
         (= (persones res9) 4)
         (= (principi res9) 4)
         (= (final res9) 24)
         (= (persones res10) 1)
         (= (principi res10) 22)
         (= (final res10) 23)
         (= (persones res11) 4)
         (= (principi res11) 3)
         (= (final res11) 6)
         (= (persones res12) 2)
         (= (principi res12) 22)
         (= (final res12) 30)
         (= (persones res13) 2)
         (= (principi res13) 29)
         (= (final res13) 30)
         (= (persones res14) 2)
         (= (principi res14) 8)
         (= (final res14) 25)
         (= (persones res15) 1)
         (= (principi res15) 23)
         (= (final res15) 25)
         (= (persones res16) 4)
         (= (principi res16) 13)
         (= (final res16) 16)
         (= (persones res17) 2)
         (= (principi res17) 1)
         (= (final res17) 5)
         (= (persones res18) 2)
         (= (principi res18) 19)
         (= (final res18) 28)
         (= (persones res19) 3)
         (= (principi res19) 15)
         (= (final res19) 18)
         (= (persones res20) 2)
         (= (principi res20) 11)
         (= (final res20) 23)
         (= (persones res21) 2)
         (= (principi res21) 22)
         (= (final res21) 24)
         (= (persones res22) 2)
         (= (principi res22) 15)
         (= (final res22) 26)
         (= (persones res23) 2)
         (= (principi res23) 21)
         (= (final res23) 30)
         (= (persones res24) 3)
         (= (principi res24) 23)
         (= (final res24) 29)
         (= (reserves-no-satisfetes) 0)
         (= (habitacions-obertes) 0)
         (= (desaprofitament-places) 0)
         (not (decidida hab0))
         (not (decidida hab1))
         (not (decidida hab2))
         (not (decidida hab3))
         (not (decidida hab4))
         (not (decidida hab5))
         (not (decidida hab6))
         (not (decidida hab7))
         (not (decidida hab8))
         (not (decidida hab9))
         (not (decidida hab10))
         (not (decidida hab11))
         (not (decidida hab12))
         (not (decidida hab13))
         (not (decidida hab14))
         (not (decidida hab15))
         (not (decidida hab16))
         (not (decidida hab17))
         (not (decidida hab18))
         (not (decidida hab19))
         (not (decidida hab20))
         (not (decidida hab21))
         (not (decidida hab22))
         (not (decidida hab23))
         (not (decidida hab24))
   )
   (:goal  (and (forall (?res - reserva) (processada ?res)) (forall (?res - habitacio) (decidida ?res))))
   (:metric minimize (+ (+ (* 1 (reserves-no-satisfetes)) (* 1 (desaprofitament-places))) (* 1 (habitacions-obertes))))
)
