(define (problem problema-h5-r5)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 - habitacio
             res0 res1 res2 res3 res4 - reserva)
   (:init
         (= (capacitat hab0) 4)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 2)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 2)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 2)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 2)
         (= (ultim-dia-ocupada hab4) 0)
         (= (persones res0) 3)
         (= (principi res0) 2)
         (= (final res0) 29)
         (= (persones res1) 1)
         (= (principi res1) 20)
         (= (final res1) 22)
         (= (persones res2) 3)
         (= (principi res2) 27)
         (= (final res2) 30)
         (= (persones res3) 1)
         (= (principi res3) 2)
         (= (final res3) 30)
         (= (persones res4) 3)
         (= (principi res4) 20)
         (= (final res4) 28)
         (= (reserves-no-satisfetes) 0)
         (= (desaprofitament-places) 0)
   )
   (:goal (forall (?res - reserva) (processada ?res)))
   (:metric minimize (+ (* 1 (reserves-no-satisfetes)) (* 1 (desaprofitament-places))))
)
