(define (problem problema-h3-r3)
   (:domain reserves)
   (:objects hab0 hab1 hab2 - habitacio
             res0 res1 res2 - reserva)
   (:init
         (= (capacitat hab0) 2)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 3)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 4)
         (= (ultim-dia-ocupada hab2) 0)
         (= (persones res0) 1)
         (= (principi res0) 5)
         (= (final res0) 6)
         (= (persones res1) 2)
         (= (principi res1) 18)
         (= (final res1) 25)
         (= (persones res2) 2)
         (= (principi res2) 27)
         (= (final res2) 30)
         (= (reserves-no-satisfetes) 0)
         (= (habitacions-obertes) 0)
         (= (desaprofitament-places) 0)
   )
   (:goal  (and (forall (?res - reserva) (processada ?res)) (forall (?hab - habitacio) (decidida ?hab))))
   (:metric minimize (+ (+ (* 1 (reserves-no-satisfetes)) (* 1 (desaprofitament-places))) (* 1 (habitacions-obertes))))
)
