(define (problem problema-h15-r15)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 hab5 hab6 hab7 hab8 hab9 hab10 hab11 hab12 hab13 hab14 - habitacio
             res0 res1 res2 res3 res4 res5 res6 res7 res8 res9 res10 res11 res12 res13 res14 - reserva)
   (:init
         (= (capacitat hab0) 1)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 1)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 3)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 1)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 4)
         (= (ultim-dia-ocupada hab4) 0)
         (= (capacitat hab5) 3)
         (= (ultim-dia-ocupada hab5) 0)
         (= (capacitat hab6) 1)
         (= (ultim-dia-ocupada hab6) 0)
         (= (capacitat hab7) 4)
         (= (ultim-dia-ocupada hab7) 0)
         (= (capacitat hab8) 2)
         (= (ultim-dia-ocupada hab8) 0)
         (= (capacitat hab9) 3)
         (= (ultim-dia-ocupada hab9) 0)
         (= (capacitat hab10) 3)
         (= (ultim-dia-ocupada hab10) 0)
         (= (capacitat hab11) 4)
         (= (ultim-dia-ocupada hab11) 0)
         (= (capacitat hab12) 1)
         (= (ultim-dia-ocupada hab12) 0)
         (= (capacitat hab13) 1)
         (= (ultim-dia-ocupada hab13) 0)
         (= (capacitat hab14) 2)
         (= (ultim-dia-ocupada hab14) 0)
         (= (persones res0) 3)
         (= (principi res0) 9)
         (= (final res0) 20)
         (= (persones res1) 1)
         (= (principi res1) 15)
         (= (final res1) 30)
         (= (persones res2) 1)
         (= (principi res2) 16)
         (= (final res2) 20)
         (= (persones res3) 1)
         (= (principi res3) 2)
         (= (final res3) 13)
         (= (persones res4) 4)
         (= (principi res4) 8)
         (= (final res4) 15)
         (= (persones res5) 1)
         (= (principi res5) 8)
         (= (final res5) 27)
         (= (persones res6) 4)
         (= (principi res6) 13)
         (= (final res6) 16)
         (= (persones res7) 2)
         (= (principi res7) 29)
         (= (final res7) 30)
         (= (persones res8) 3)
         (= (principi res8) 18)
         (= (final res8) 19)
         (= (persones res9) 2)
         (= (principi res9) 7)
         (= (final res9) 11)
         (= (persones res10) 2)
         (= (principi res10) 1)
         (= (final res10) 29)
         (= (persones res11) 4)
         (= (principi res11) 18)
         (= (final res11) 26)
         (= (persones res12) 4)
         (= (principi res12) 18)
         (= (final res12) 27)
         (= (persones res13) 3)
         (= (principi res13) 29)
         (= (final res13) 30)
         (= (persones res14) 3)
         (= (principi res14) 20)
         (= (final res14) 22)
         (= (reserves-no-satisfetes) 0)
         (= (habitacions-obertes) 0)
         (= (desaprofitament-places) 0)
   )
   (:goal  (and (forall (?res - reserva) (processada ?res)) (forall (?hab - habitacio) (decidida ?hab))))
   (:metric minimize (+ (+ (* 1 (reserves-no-satisfetes)) (* 1 (desaprofitament-places))) (* 1 (habitacions-obertes))))
)
