(define (problem problema-h15-r15)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 hab5 hab6 hab7 hab8 hab9 hab10 hab11 hab12 hab13 hab14 - habitacio
             res0 res1 res2 res3 res4 res5 res6 res7 res8 res9 res10 res11 res12 res13 res14 - reserva)
   (:init
         (= (capacitat hab0) 4)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 1)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 4)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 1)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 1)
         (= (ultim-dia-ocupada hab4) 0)
         (= (capacitat hab5) 2)
         (= (ultim-dia-ocupada hab5) 0)
         (= (capacitat hab6) 3)
         (= (ultim-dia-ocupada hab6) 0)
         (= (capacitat hab7) 3)
         (= (ultim-dia-ocupada hab7) 0)
         (= (capacitat hab8) 2)
         (= (ultim-dia-ocupada hab8) 0)
         (= (capacitat hab9) 4)
         (= (ultim-dia-ocupada hab9) 0)
         (= (capacitat hab10) 3)
         (= (ultim-dia-ocupada hab10) 0)
         (= (capacitat hab11) 2)
         (= (ultim-dia-ocupada hab11) 0)
         (= (capacitat hab12) 1)
         (= (ultim-dia-ocupada hab12) 0)
         (= (capacitat hab13) 4)
         (= (ultim-dia-ocupada hab13) 0)
         (= (capacitat hab14) 1)
         (= (ultim-dia-ocupada hab14) 0)
         (= (persones res0) 4)
         (= (principi res0) 6)
         (= (final res0) 22)
         (= (persones res1) 2)
         (= (principi res1) 9)
         (= (final res1) 26)
         (= (persones res2) 1)
         (= (principi res2) 21)
         (= (final res2) 25)
         (= (persones res3) 1)
         (= (principi res3) 10)
         (= (final res3) 23)
         (= (persones res4) 4)
         (= (principi res4) 29)
         (= (final res4) 30)
         (= (persones res5) 1)
         (= (principi res5) 22)
         (= (final res5) 30)
         (= (persones res6) 3)
         (= (principi res6) 29)
         (= (final res6) 30)
         (= (persones res7) 3)
         (= (principi res7) 26)
         (= (final res7) 27)
         (= (persones res8) 2)
         (= (principi res8) 21)
         (= (final res8) 27)
         (= (persones res9) 4)
         (= (principi res9) 25)
         (= (final res9) 28)
         (= (persones res10) 3)
         (= (principi res10) 17)
         (= (final res10) 22)
         (= (persones res11) 2)
         (= (principi res11) 3)
         (= (final res11) 15)
         (= (persones res12) 4)
         (= (principi res12) 7)
         (= (final res12) 9)
         (= (persones res13) 4)
         (= (principi res13) 14)
         (= (final res13) 20)
         (= (persones res14) 1)
         (= (principi res14) 4)
         (= (final res14) 23)
         (= (reserves-no-satisfetes) 0)
         (= (habitacions-obertes) 0)
         (= (desaprofitament-places) 0)
         (not (decidida hab0))
         (not (decidida hab1))
         (not (decidida hab2))
         (not (decidida hab3))
         (not (decidida hab4))
         (not (decidida hab5))
         (not (decidida hab6))
         (not (decidida hab7))
         (not (decidida hab8))
         (not (decidida hab9))
         (not (decidida hab10))
         (not (decidida hab11))
         (not (decidida hab12))
         (not (decidida hab13))
         (not (decidida hab14))
   )
   (:goal  (and (forall (?res - reserva) (processada ?res)) (forall (?res - habitacio) (decidida ?res))))
   (:metric minimize (+ (+ (* 1 (reserves-no-satisfetes)) (* 1 (desaprofitament-places))) (* 1 (habitacions-obertes))))
)
