(define (problem problema-h15-r15)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 hab5 hab6 hab7 hab8 hab9 hab10 hab11 hab12 hab13 hab14 - habitacio
             res0 res1 res2 res3 res4 res5 res6 res7 res8 res9 res10 res11 res12 res13 res14 - reserva)
   (:init
         (= (capacitat hab0) 1)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 4)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 2)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 4)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 4)
         (= (ultim-dia-ocupada hab4) 0)
         (= (capacitat hab5) 1)
         (= (ultim-dia-ocupada hab5) 0)
         (= (capacitat hab6) 3)
         (= (ultim-dia-ocupada hab6) 0)
         (= (capacitat hab7) 3)
         (= (ultim-dia-ocupada hab7) 0)
         (= (capacitat hab8) 1)
         (= (ultim-dia-ocupada hab8) 0)
         (= (capacitat hab9) 4)
         (= (ultim-dia-ocupada hab9) 0)
         (= (capacitat hab10) 3)
         (= (ultim-dia-ocupada hab10) 0)
         (= (capacitat hab11) 1)
         (= (ultim-dia-ocupada hab11) 0)
         (= (capacitat hab12) 4)
         (= (ultim-dia-ocupada hab12) 0)
         (= (capacitat hab13) 2)
         (= (ultim-dia-ocupada hab13) 0)
         (= (capacitat hab14) 4)
         (= (ultim-dia-ocupada hab14) 0)
         (= (persones res0) 4)
         (= (principi res0) 15)
         (= (final res0) 25)
         (= (persones res1) 2)
         (= (principi res1) 17)
         (= (final res1) 21)
         (= (persones res2) 3)
         (= (principi res2) 1)
         (= (final res2) 2)
         (= (persones res3) 3)
         (= (principi res3) 19)
         (= (final res3) 28)
         (= (persones res4) 3)
         (= (principi res4) 29)
         (= (final res4) 30)
         (= (persones res5) 1)
         (= (principi res5) 29)
         (= (final res5) 30)
         (= (persones res6) 3)
         (= (principi res6) 2)
         (= (final res6) 22)
         (= (persones res7) 2)
         (= (principi res7) 19)
         (= (final res7) 23)
         (= (persones res8) 2)
         (= (principi res8) 12)
         (= (final res8) 16)
         (= (persones res9) 2)
         (= (principi res9) 22)
         (= (final res9) 30)
         (= (persones res10) 4)
         (= (principi res10) 28)
         (= (final res10) 30)
         (= (persones res11) 1)
         (= (principi res11) 19)
         (= (final res11) 21)
         (= (persones res12) 2)
         (= (principi res12) 23)
         (= (final res12) 26)
         (= (persones res13) 2)
         (= (principi res13) 4)
         (= (final res13) 20)
         (= (persones res14) 3)
         (= (principi res14) 29)
         (= (final res14) 30)
         (= (reserves-no-satisfetes) 0)
         (= (desaprofitament-places) 0)
   )
   (:goal (forall (?res - reserva) (processada ?res)))
   (:metric minimize (+ (* 1 (reserves-no-satisfetes)) (* 1 (desaprofitament-places))))
)
