(define (problem problema-h5-r5)
   (:domain reserves)
   (:objects hab0 hab1 hab2 hab3 hab4 - habitacio
             res0 res1 res2 res3 res4 - reserva)
   (:init
         (= (capacitat hab0) 3)
         (= (ultim-dia-ocupada hab0) 0)
         (= (capacitat hab1) 3)
         (= (ultim-dia-ocupada hab1) 0)
         (= (capacitat hab2) 3)
         (= (ultim-dia-ocupada hab2) 0)
         (= (capacitat hab3) 2)
         (= (ultim-dia-ocupada hab3) 0)
         (= (capacitat hab4) 1)
         (= (ultim-dia-ocupada hab4) 0)
         (= (persones res0) 3)
         (= (principi res0) 14)
         (= (final res0) 18)
         (= (persones res1) 1)
         (= (principi res1) 21)
         (= (final res1) 26)
         (= (persones res2) 1)
         (= (principi res2) 15)
         (= (final res2) 21)
         (= (persones res3) 2)
         (= (principi res3) 10)
         (= (final res3) 24)
         (= (persones res4) 4)
         (= (principi res4) 23)
         (= (final res4) 29)
         (= (reserves-no-satisfetes) 0)
         (= (habitacions-obertes) 0)
         (= (desaprofitament-places) 0)
         (not (decidida hab0))
         (not (decidida hab1))
         (not (decidida hab2))
         (not (decidida hab3))
         (not (decidida hab4))
   )
   (:goal  (and (forall (?res - reserva) (processada ?res)) (forall (?res - habitacio) (decidida ?res))))
   (:metric minimize (+ (+ (* 1 (reserves-no-satisfetes)) (* 1 (desaprofitament-places))) (* 1 (habitacions-obertes))))
)
